# Generated by Django 3.0.2 on 2020-02-01 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
